# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('last_name', models.TextField(verbose_name='last name')),
                ('second_name', models.TextField(verbose_name='second name')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='image')),
                ('title', models.TextField(verbose_name='title')),
                ('date_of_publication', models.DateField(verbose_name='date of publication')),
                ('description', models.TextField(verbose_name='description')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books_app.Author', verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
            ],
        ),
    ]
