# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_app.Genre', verbose_name='genre'),
        ),
    ]
