# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0004_auto_20170708_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='test_path_img',
            field=models.ImageField(blank=True, upload_to='test_path', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='book',
            name='test_path_txt',
            field=models.FileField(blank=True, upload_to='test_path', verbose_name='*.txt'),
        ),
        migrations.AddField(
            model_name='book',
            name='test_pathfb2',
            field=models.FileField(blank=True, upload_to='test_path', verbose_name='*.fb2'),
        ),
    ]
