# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0005_auto_20170709_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='test_path_img',
        ),
        migrations.RemoveField(
            model_name='book',
            name='test_path_txt',
        ),
        migrations.RemoveField(
            model_name='book',
            name='test_pathfb2',
        ),
        migrations.AddField(
            model_name='book',
            name='file_fb2',
            field=models.FileField(blank=True, upload_to='test', verbose_name='*.fb2'),
        ),
        migrations.AddField(
            model_name='book',
            name='file_txt',
            field=models.FileField(blank=True, upload_to='test', verbose_name='*.txt'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='test', verbose_name='image'),
        ),
    ]
