# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0007_auto_20170709_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
    ]
