# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0012_auto_20170709_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleOfStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=126, verbose_name='title')),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='second_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='second name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='books_app.Author', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_of_publication',
            field=models.DateField(blank=True, verbose_name='date of publication'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, to='books_app.Genre', verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=126, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='cycleofstories',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='books_app.Author', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='book',
            name='cycle',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='books_app.CycleOfStories', verbose_name='cycle of stories'),
            preserve_default=False,
        ),
    ]
