# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0013_auto_20170709_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_of_publication',
        ),
        migrations.AddField(
            model_name='book',
            name='year_of_publication',
            field=models.IntegerField(blank=True, default=2000, max_length=4, verbose_name='year of publication'),
        ),
    ]
