# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 17:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0014_auto_20170709_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='year_of_publication',
            field=models.PositiveIntegerField(blank=True, default=2017, validators=[django.core.validators.MaxValueValidator(2017)], verbose_name='year of publication'),
        ),
    ]
