# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0015_auto_20170709_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='books_app.Genre', verbose_name='genre'),
        ),
    ]
