# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_path', models.TextField(verbose_name='path')),
                ('name', models.TextField(verbose_name='name')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
    ]
