# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='icon_path',
            field=models.TextField(blank=True, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.TextField(blank=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(blank=True, verbose_name='text'),
        ),
    ]
