# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170510_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Card', verbose_name='booster')),
            ],
        ),
    ]
