# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_booster'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='color',
            field=models.TextField(blank=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='booster',
            name='name',
            field=models.TextField(blank=True, verbose_name='name'),
        ),
    ]
