# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20170510_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='icon_path',
            new_name='img',
        ),
        migrations.AddField(
            model_name='booster',
            name='price',
            field=models.TextField(blank=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='card',
            name='manacost',
            field=models.TextField(blank=True, verbose_name='manacost'),
        ),
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.TextField(blank=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='booster',
            name='cards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Card', verbose_name='card'),
        ),
    ]
