# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20170510_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='', upload_to='card_images', verbose_name='image'),
            preserve_default=False,
        ),
    ]
