# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manacost', models.TextField(blank=True, verbose_name='manacost')),
                ('img', models.TextField(blank=True, verbose_name='path')),
                ('name', models.TextField(blank=True, verbose_name='name')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('price', models.TextField(blank=True, verbose_name='price')),
                ('image', models.ImageField(upload_to='card_images', verbose_name='image')),
            ],
        ),
    ]
