# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_app', '0002_auto_20170515_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='edition',
            field=models.TextField(blank=True, verbose_name='edition'),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.TextField(blank=True, verbose_name='rarity'),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.TextField(blank=True, verbose_name='type'),
        ),
    ]
