# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='name')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('mileage', models.IntegerField(blank=True, verbose_name='mileage')),
                ('doors', models.IntegerField(blank=True, verbose_name='doors')),
                ('engines_type', models.TextField(blank=True, verbose_name='engines_type')),
                ('max_power', models.IntegerField(blank=True, verbose_name='max_power')),
                ('max_speed', models.IntegerField(blank=True, verbose_name='max_speed')),
                ('acceleration_time', models.IntegerField(blank=True, verbose_name='acceleration_time')),
                ('fuel_consumption', models.IntegerField(blank=True, verbose_name='fuel_consumption')),
                ('transmission', models.TextField(blank=True, verbose_name='transmission')),
                ('drive_unit', models.TextField(blank=True, verbose_name='drive_unit')),
                ('seat_number', models.IntegerField(blank=True, verbose_name='seat_number')),
                ('length', models.IntegerField(blank=True, verbose_name='length')),
                ('trunk_volume', models.IntegerField(blank=True, verbose_name='trunk_volume')),
                ('days1_2', models.IntegerField(blank=True, verbose_name='days1_2')),
                ('days3_6', models.IntegerField(blank=True, verbose_name='days3_6')),
                ('days7_14', models.IntegerField(blank=True, verbose_name='days7_14')),
                ('days15_30', models.IntegerField(blank=True, verbose_name='days15_30')),
                ('month1_2', models.IntegerField(blank=True, verbose_name='month1_2')),
                ('deposit', models.IntegerField(blank=True, verbose_name='deposit')),
                ('image', models.ImageField(upload_to='img', verbose_name='image')),
            ],
        ),
    ]
