# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atprokat_app', '0002_auto_20170616_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='date')),
                ('title', models.TextField(blank=True, verbose_name='title')),
                ('text', models.TextField(blank=True, verbose_name='text')),
            ],
        ),
    ]
